# This file was generated by GoReleaser. DO NOT EDIT.
class GoCLI < Formula
  desc "A fun go TUI, not a CLI"
  homepage "https://github.com/bestras-test-org/go-cli"
  version "1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/CamiloGarciaLaRotta/gifhub/releases/download/v0.3.1/gifhub_0.3.1_Darwin_x86_64.tar.gz"
    sha256 "09b06922373ff17ac61c6c30f195724aa0957387e9858ac958e3d2441340db1e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/CamiloGarciaLaRotta/gifhub/releases/download/v0.3.1/gifhub_0.3.1_Linux_x86_64.tar.gz"
      sha256 "9403c2af368a8f306e60d7c1cba35cbde6860403240f4d50fbcf7251989eb9d8"
    end
  end

  def install
    bin.install "go-cli"
  end

  test do
    system "#{bin}/gifhub"
  end
end
